Port to typescrip, added 2 endpoints, added readme
eyedea-io/syncano-socket-gm pull request #1
Opened 2018-11-06 12:55 UTC by ksyhoo

2018-11-06 13:02 UTC, olapinska commented on socket.yml
>    resize:
remove empty line

2018-11-06 14:44 UTC, mkucharz requested changes

2018-11-06 14:44 UTC, mkucharz commented on README.md
> +[![CircleCI branch](https://img.shields.io/circleci/project/github/eyedea-io/syncano-socket-<name>/master.svg)](https://circleci.com/gh/eyedea-io/syncano-socket-<name>/tree/master)
Replace all `<name>`.

2018-11-06 14:44 UTC, mkucharz commented on socket.yml
>      parameters:
New version is with `inputs` and `outputs`, please adjust.

2018-11-06 14:44 UTC, mkucharz commented on socket.yml
> +      fail:
Looks like all here is mixed. Inputs/outputs/parameters etc.

2018-11-06 14:44 UTC, mkucharz commented on socket.yml
> +        mimetype: json
no such `mimetype`

2018-11-09 20:21 UTC, mkucharz requested changes

2018-11-14 10:42 UTC, mkucharz approved these changes

2018-11-24 09:03 UTC, merged